apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  labels:
    function: app
spec:
  containers:
  - name: django
    image: ghcr.io/radiokame/cis-92:milestone-06.1
    ports:
    - containerPort: 8000
    resources:
      requests:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
    env:
    - name: STUDENT_NAME
      value: "Luis Garcia"
    - name: SITE_NAME
      value: "*"